using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Octokit;

namespace ALAN.Core.GitHub;

/// <summary>
/// Configuration for GitHub integration
/// </summary>
public class GitHubConfig
{
    public string Token { get; set; } = string.Empty;
    public string RepositoryOwner { get; set; } = string.Empty;
    public string RepositoryName { get; set; } = string.Empty;
    public string BranchName { get; set; } = "main";
}

/// <summary>
/// Service for interacting with GitHub repository
/// </summary>
public class GitHubService
{
    private readonly GitHubClient _client;
    private readonly GitHubConfig _config;
    private readonly ILogger<GitHubService> _logger;

    public GitHubService(GitHubConfig config, ILogger<GitHubService> logger)
    {
        _config = config;
        _logger = logger;
        
        _client = new GitHubClient(new ProductHeaderValue("ALAN-Agent"))
        {
            Credentials = new Credentials(config.Token)
        };
    }

    /// <summary>
    /// Get the latest code from the repository
    /// </summary>
    public async Task<IEnumerable<RepositoryContent>> GetRepositoryContentsAsync(string path = "", CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Fetching repository contents from {Owner}/{Repo}/{Path}", 
                _config.RepositoryOwner, _config.RepositoryName, path);

            var contents = await _client.Repository.Content.GetAllContents(
                _config.RepositoryOwner, 
                _config.RepositoryName, 
                path);

            return contents;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to fetch repository contents");
            throw;
        }
    }

    /// <summary>
    /// Get file content from the repository
    /// </summary>
    public async Task<string> GetFileContentAsync(string path, CancellationToken cancellationToken = default)
    {
        try
        {
            var contents = await _client.Repository.Content.GetAllContents(
                _config.RepositoryOwner,
                _config.RepositoryName,
                path);

            return contents.First().Content;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get file content for {Path}", path);
            throw;
        }
    }

    /// <summary>
    /// Create a pull request with proposed changes (requires human approval)
    /// </summary>
    public async Task<PullRequest> CreatePullRequestAsync(
        string title,
        string body,
        string headBranch,
        string baseBranch,
        CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Creating pull request: {Title}", title);

            var newPullRequest = new NewPullRequest(title, headBranch, baseBranch)
            {
                Body = $@"## AI-Generated Improvement Proposal

{body}

---
⚠️ **IMPORTANT**: This pull request was automatically generated by the ALAN autonomous agent.
Please review carefully before merging. Human approval is required for all AI-generated changes.

**Safety Checklist:**
- [ ] Code changes have been reviewed for correctness
- [ ] No security vulnerabilities introduced
- [ ] Tests pass successfully
- [ ] Changes align with project goals
"
            };

            var pullRequest = await _client.PullRequest.Create(
                _config.RepositoryOwner,
                _config.RepositoryName,
                newPullRequest);

            _logger.LogInformation("Created pull request #{Number}", pullRequest.Number);
            return pullRequest;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to create pull request");
            throw;
        }
    }

    /// <summary>
    /// Analyze code and propose improvements
    /// </summary>
    public async Task<CodeAnalysisResult> AnalyzeCodeAsync(string filePath, CancellationToken cancellationToken = default)
    {
        try
        {
            var content = await GetFileContentAsync(filePath, cancellationToken);
            
            // Simple analysis - in a real implementation, this would use AI to analyze the code
            var result = new CodeAnalysisResult
            {
                FilePath = filePath,
                Content = content,
                Suggestions = new List<string>
                {
                    "File successfully retrieved and ready for AI analysis"
                }
            };

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to analyze code for {FilePath}", filePath);
            throw;
        }
    }
}

/// <summary>
/// Result of code analysis
/// </summary>
public class CodeAnalysisResult
{
    public string FilePath { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public List<string> Suggestions { get; set; } = new();
}
